# Generated by Django 4.2.4 on 2023-09-20 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(choices=[(0, 'NO ACTIVE'), (1, 'ACTIVE')], default=1)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post')),
            ],
            options={
                'verbose_name': 'Клментарий',
                'verbose_name_plural': 'Коментарии',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['created'], name='blog_commen_created_01a762_idx')],
            },
        ),
    ]
