# Generated by Django 4.2.4 on 2023-09-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremierMatches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=200, verbose_name='Название премьеры игры')),
                ('photo', models.TextField()),
                ('href_premier', models.TextField()),
            ],
            options={
                'verbose_name': 'Премьера матча',
                'verbose_name_plural': 'Премьеры матчей',
            },
        ),
    ]
