# Generated by Django 4.2.4 on 2023-09-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_premiermatches'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='twitch_stream',
            field=models.TextField(blank=True, null=True, verbose_name='Сылка на твитч стрим'),
        ),
        migrations.AlterField(
            model_name='game',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='game',
            name='peculiarities',
            field=models.ManyToManyField(blank=True, null=True, related_name='games', to='games.peculiarities'),
        ),
    ]
