# Generated by Django 4.2.4 on 2023-09-08 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_game_peculiarities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='twitch_stream',
        ),
    ]
