# Generated by Django 4.2.4 on 2023-09-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_remove_game_twitch_stream'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameTop100',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=100, verbose_name='Название стрима')),
                ('href', models.TextField()),
            ],
        ),
    ]
