# Generated by Django 4.2.4 on 2023-09-11 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_gametop100'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameTop100',
            new_name='GameTop30TwitchStream',
        ),
        migrations.RenameField(
            model_name='premiermatches',
            old_name='href_premier',
            new_name='href',
        ),
    ]
